In [1]:
import tensorflow as tf
import matplotlib.image as mpimg
import matplotlib.pyplot as plt
import os
import numpy as np
import pickle
import matplotlib
from sklearn.metrics import confusion_matrix

np.set_printoptions(precision=3, suppress=True)

In [2]:
X_train = np.matrix([[1],[0]])
Y_train = np.matrix([[0],[1]])

In [7]:
def sigmoid(x):
    # x = 64*N matrix
    return 1. / (1 + np.exp(-x))

In [8]:
def softmax_matrix(x):
    # x = 5*N matrix
    return np.exp(x) / np.sum(np.exp(x), axis = 0)

In [9]:
def compute_loss_matrix(Y_hat, Y):
    # Y, Y_hat = 5*N matrix
    return -1 / Y.shape[1] * np.sum(np.multiply(Y, np.log(Y_hat)))

In [18]:
W1 = np.matrix([[3.,6.],[4.,5.]])
b1 = np.matrix([[1.],[-6.]])
W2 = np.matrix([[2.,3.],[4.,3.]])
b2 = np.matrix([[-1.],[-2.]])

In [19]:
lr = 0.5
X = X_train
Y = Y_train
for i in range(1):
    A1 = np.matmul(W1.T, X) + b1 # 64*25112
    Z1 = sigmoid(A1) # 64*25112
    
    A2 = np.matmul(W2.T, Z1) + b2 # 5*25112
    Y_hat = softmax_matrix(A2) # 5*25112

    loss = compute_loss_matrix(Y_hat, Y)
    
    dW2 = Z1 * (Y_hat-Y).T # 64*5 = (64*25112) * (25112*5)
    db2 = np.sum(Y_hat-Y, axis = 1) # 64*1
    
    dZ1 = W2 * (Y_hat-Y) # (64*5) * (5*25112)
    dA1 = np.multiply(dZ1, np.multiply(sigmoid(A1), 1-sigmoid(A1))) # 64*25112
    dW1 = X * dA1.T # (784*25112) * (25112*64)
    db1 = np.sum(dA1, axis = 1) # 64*1

    W2 -= lr * dW2
    b2 -= lr * db2
    W1 -= lr * dW1
    b1 -= lr * db1
    
    print('A1: \n', A1)
    print('Z1: \n', Z1)
    print('A2: \n', A2)
    print('Y_hat: \n', Y_hat)
    print('loss: \n', loss)
    
    print('dW2: \n', dW2)
    print('db2: \n', db2)
    print('dW1: \n', dW1)
    print('db1: \n', db1)
    
    print('W2: \n', W2)
    print('b2: \n', b2)
    print('W1: \n', W1)
    print('b1: \n', b1)
    
#     if i % 100 == 0:
    print('Iter: {}\tloss: {}'.format(i, loss))

A1: 
 [[4.]
 [0.]]
Z1: 
 [[0.982]
 [0.5  ]]
A2: 
 [[2.964]
 [2.446]]
Y_hat: 
 [[0.627]
 [0.373]]
loss: 
 0.985310624459659
dW2: 
 [[ 0.615 -0.615]
 [ 0.313 -0.313]]
db2: 
 [[ 0.627]
 [-0.627]]
dW1: 
 [[-0.011  0.157]
 [ 0.     0.   ]]
db1: 
 [[-0.011]
 [ 0.157]]
W2: 
 [[1.692 3.308]
 [3.843 3.157]]
b2: 
 [[-1.313]
 [-1.687]]
W1: 
 [[3.006 5.922]
 [4.    5.   ]]
b1: 
 [[ 1.006]
 [-6.078]]
Iter: 0	loss: 0.985310624459659


In [15]:
np.matmul(W1.T, X) + b1

matrix([[4.],
        [0.]])